[shell]
program = "/bin/zsh"
args = [
"-l",
"-c",
"/opt/homebrew/bin/zellij attach home || /opt/homebrew/bin/zellij -s home"
]

[window]
option_as_alt = "Both"
startup_mode="Fullscreen"

[font]
size = 18
normal.family = "GoMono Nerd Font"
